version: "3.9"
services:
  frontend:
    image: "2e0253b64a8/frontend"
    ports:
      - "3000:3000"
    restart: always
  backend:
    image: "2e0253b64a8/backend"
    ports:
      - "4000:4000"
    restart: always
    environment:
      UPLOAD_DIR: /app/pv/images
      DB_ADDR: mongodb
      FRONTEND_URL: https://e-luborzyca.pl
      SESSION_TOKEN_TTL: 31536000
      # SMTP_HOST:
      # SMTP_PORT:
      # SMTP_USER:
      # SMTP_PASSWORD:
      # SMTP_SENDER_NAME:
      # SMTP_SKIP_CERT_CHECK:
    volumes:
      - eluborzyca_backend_pv:/app/pv
  mongodb:
    image: "mongo:4.4.3"
    volumes:
      - eluborzyca_mongodb_pv:/data
  haproxy:
    image: haproxy:1.7
    ports:  
      - 80:80
      - 443:443
    volumes:
      - '/usr/local/etc/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro'
      - '/etc/ssl/e-luborzyca.pl/:/etc/ssl/e-luborzyca.pl/:ro'
  adminMongo:
    image: "imilindsingh/admin-mongo"
    ports:
      - "1234:1234"
    restart: always
    volumes:
      - '/usr/local/etc/adminMongo.json:/app/admin-mongo/config/app.json:ro'

volumes:
  # docker volume create -d local-persist -o mountpoint=/mnt/eluborzyca_backend_pv --name=eluborzyca_backend_pv
  eluborzyca_backend_pv:
    external: true
  # docker volume create -d local-persist -o mountpoint=/mnt/eluborzyca_mongodb_pv --name=eluborzyca_mongodb_pv
  eluborzyca_mongodb_pv:
    external: true