version: "3.9"
services:
  frontend:
    image: "2e0253b64a8/frontend"
    ports:
      - "3000:3000"
    restart: always
  backend:
    image: "2e0253b64a8/backend"
    ports:
      - "4000:4000"
    restart: always
    environment:
      UPLOAD_DIR: /app/pv/images
      DB_ADDR: mongodb
    volumes:
      - eluborzyca_backend_pv:/app/pv
  mongodb:
    image: "mongo:4.4"
  haproxy:
    image: haproxy:1.7
    ports:  
      - 80:80
      - 443:443
    volumes:
      - '/usr/local/etc/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro'

volumes:
  # docker volume create -d local-persist -o mountpoint=/mnt/eluborzyca_backend_pv --name=eluborzyca_backend_pv
  eluborzyca_backend_pv:
    external: true